Addition of a simple Hexa8 example
isaar/MSolve pull request #40
Opened 2016-09-17 18:49 UTC by teojgo

Add an illustrative example documenting the required steps to solve a simple static linear problem with MSolve.

2016-10-10 10:55 UTC, GoatOfRafin requested changes
Please commit needed files only (cs files and csproj if it is altered) and write more concise code WITHOUT UNNECESSARY comments.

2016-10-10 10:55 UTC, GoatOfRafin commented on FEMElements/FEMElements.sln
>  ﻿
Remove solution file from your pull request since it does not reflect any actual code changes.

2016-10-10 10:55 UTC, GoatOfRafin commented on ISAAR.MSolve.Logging/packages.config
> +﻿<?xml version="1.0" encoding="utf-8"?>
Remove packages.config file from your pull request since it does not reflect any actual code changes.

2016-10-10 10:55 UTC, GoatOfRafin commented on ISAAR.MSolve.SamplesConsole/Examples/Static/Linear/Hexa8SimpleExample.cs
> +            IList<Node> nodes = new List<Node>();
Be more concise by adding the nodes like this:

nodes.Add(new Node { ID = 1, X = 0.0, Y = 0.0, Z= 0.0 });

2016-10-10 10:55 UTC, GoatOfRafin commented on ISAAR.MSolve.SamplesConsole/Examples/Static/Linear/Hexa8SimpleExample.cs
> +            // Constraint bottom nodes of the model
Add a for loop from 1 to 4, constraining the nodes. Too many lines for this and no need for loop unrolling!

2016-10-10 10:55 UTC, GoatOfRafin commented on ISAAR.MSolve.SamplesConsole/Examples/Static/Linear/Hexa8SimpleExample.cs
> +            element.AddNode(model.NodesDictionary[1]);
Remove solution file from your pull request since it does not reflect any actual code changes.

2016-10-10 10:55 UTC, GoatOfRafin commented on ISAAR.MSolve.SamplesConsole/Examples/Static/Linear/Hexa8SimpleExample.cs
> +            model.Loads.Add(new Load() { Amount = -nodalLoad, Node = model.NodesDictionary[5], DOF = DOFType.Z });
Remove solution file from your pull request since it does not reflect any actual code changes.

2016-10-10 10:55 UTC, GoatOfRafin commented on ISAAR.MSolve.SamplesConsole/Examples/Static/Linear/Hexa8SimpleExample.cs
> +            // Node creation
Remove all UNNECESSARY comments like // Create nodes and then a line like nodes = CreateNodes().

2016-10-10 10:55 UTC, GoatOfRafin commented on ISAAR.MSolve.SamplesConsole/packages.config
> +﻿<?xml version="1.0" encoding="utf-8"?>
Thrower package is not in the library, please remove or explain why it is needed so that it can be incorporated.

2016-10-10 17:50 UTC, teojgo commented on ISAAR.MSolve.SamplesConsole/packages.config
> +﻿<?xml version="1.0" encoding="utf-8"?>
Newer versions of Troschuetz.Random depend on Thrower.

2016-11-01 11:55 UTC, GoatOfRafin commented
Please re-submit at development branch

2016-11-01 11:55 UTC, closed without merging