Quad4 element and simple example
isaar/MSolve pull request #46
Opened 2016-10-17 11:35 UTC by pmetsis

Good morning everyone! I am uploading the Quad4 plane stress element. I also had to make some changes to quadrature and material. You can check the element by solving the simple example provided. Since I use Xamarin for Mac (and I haven't figured out the git extension for it yet), I have manually uploaded these files, if something else is missing please notify. Stresses/strains are not yet implemented but I couldn't comment them out for consistency reasons. I will also upload the solution of the simple example by hand or using some Matlab routines of my own in order to verify the code (I have already checked that it works).

2016-10-31 12:30 UTC, GoatOfRafin requested changes
Minor changes need to be implemented.

2016-10-31 12:30 UTC, georgestavroulakis commented on ElasticMaterial2D.cs
> +            //Panos Plane Stress
Comments like that should be left out. The proper place for such stuff is the documentation which will be constructed

2016-10-31 12:30 UTC, georgestavroulakis commented on ElasticMaterial2D.cs
> +            //afE[0, 2] = 0;
Please remove code that is commented out.

2016-10-31 12:30 UTC, GoatOfRafin commented on GaussQuadrature.cs
> +        /* For point coordinates, we encounter the following constants:
These comments should be added to the documentation

2016-10-31 12:30 UTC, GoatOfRafin commented on Quad4.cs
> +		protected static int iInt = 2;
This should be changed and input to the constructor (maybe have multiple constructors with one of them having the default gauss integration order)

2016-10-31 12:30 UTC, GoatOfRafin commented on Quad4.cs
> +        //Panos - I dont think I need these
These properties should be put to an interface that will need to be implemented for elements that support dynamic analysis

2016-10-31 12:30 UTC, GoatOfRafin commented on Quad4.cs
> +		{
All ID fields should be deleted

2016-10-31 12:30 UTC, GoatOfRafin commented on Quad4.cs
> +        {
This should be put to the documentation

2016-10-31 12:30 UTC, GoatOfRafin commented on Quad4.cs
> +                //SOS PANOS - THIS IS WRONG, I SHOULD IMPLEMENT INVERSE JACOBIAN
We should implement a generic inverse jacobian static class

2018-10-15 16:01 UTC, SerafeimBakalakos commented
This pull request has been stagnant for 2 years and the extra features have been added by other pull requests. Therefore I am closing this.

2018-10-15 16:01 UTC, closed without merging